### ISSUE TITLE
quotes around multiple cities `CITIES="nyc,portland"` causes quotes in metric name

### ISSUE THREAD

**Issue by TryTryAgain** [celliott/weather_exporter#3]
I noticed your README.md doc has the example `CITIES="nyc,portland"` but this causes prometheus to store metrics under node names `"nyc` and `portland"`.

**Comment by celliott** [comment]
@TryTryAgain Great catch. I updated the readme, but I will leave this issue open b/c I would like to rethink how I specify cities. Thx again. I appreciate the feedback.

**Comment by celliott** [comment]
Closing issue.
